FROM node:24-alpine

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package.json ./frontend/package.json
RUN npm ci

COPY frontend ./frontend

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace", "frontend"]
