"""Revocable accounts sessions MFA recovery and security audit

Revision ID: e6f3f90ba613
Revises: 8a91c04eb672
Create Date: 2026-10-10 13:21:20.431465

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e6f3f90ba613"
down_revision: str | None = "8a91c04eb672"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_mail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("encrypted_body", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "security_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "account_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reauthenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_account_sessions_user_id"), "account_sessions", ["user_id"], unique=False)
    op.create_table(
        "account_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_account_tokens_user_id"), "account_tokens", ["user_id"], unique=False)
    op.create_table(
        "privacy_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "security_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("context", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_events_action"), "security_events", ["action"], unique=False)
    op.add_column(
        "florist_profiles",
        sa.Column("application_state", sa.String(length=20), nullable=False, server_default="pending"),
    )
    op.add_column("florist_profiles", sa.Column("decision_reason", sa.Text(), nullable=False, server_default=""))
    op.add_column("users", sa.Column("role", sa.String(length=20), nullable=False, server_default="florist"))
    op.add_column("users", sa.Column("security_version", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("mfa_secret", sa.Text(), nullable=False, server_default=""))
    op.add_column("users", sa.Column("mfa_pending", sa.Text(), nullable=False, server_default=""))
    op.add_column("users", sa.Column("mfa_last_step", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("users", sa.Column("recovery_codes", sa.JSON(), nullable=False, server_default="[]"))
    op.execute("UPDATE users SET role = 'owner' WHERE is_admin = true")
    op.execute("UPDATE florist_profiles SET application_state = 'approved' WHERE approved = true")
    for table, columns in [
        ("users", ["role", "security_version", "mfa_secret", "mfa_pending", "mfa_last_step", "recovery_codes"]),
        ("florist_profiles", ["application_state", "decision_reason"]),
    ]:
        for column in columns:
            op.alter_column(table, column, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "recovery_codes")
    op.drop_column("users", "mfa_last_step")
    op.drop_column("users", "mfa_pending")
    op.drop_column("users", "mfa_secret")
    op.drop_column("users", "security_version")
    op.drop_column("users", "role")
    op.drop_column("florist_profiles", "decision_reason")
    op.drop_column("florist_profiles", "application_state")
    op.drop_index(op.f("ix_security_events_action"), table_name="security_events")
    op.drop_table("security_events")
    op.drop_table("privacy_requests")
    op.drop_index(op.f("ix_account_tokens_user_id"), table_name="account_tokens")
    op.drop_table("account_tokens")
    op.drop_index(op.f("ix_account_sessions_user_id"), table_name="account_sessions")
    op.drop_table("account_sessions")
    op.drop_table("security_throttles")
    op.drop_table("security_mail")
    # ### end Alembic commands ###
